### ISSUE TITLE
請問mac電腦程式要去那下載

### ISSUE THREAD

**Issue by wei0999** [liuw086/SuperScreen#1]
請問mac電腦程式要去那下載 謝謝

**Comment by liuw086** [comment]
这个链接：
https://github.com/liuw086/SuperScreenPC/releases/
![image](https://github.com/liuw086/SuperScreen/assets/9710022/d63289a6-3e37-4e83-98ad-1e9b3b9b5088)

**Comment by liuw086** [comment]
https://github.com/liuw086/SuperScreenPC/releases/ 
download lastest version
