### ISSUE TITLE
LAN settings screen isn't in English

### ISSUE THREAD

**Issue by PashaKagan** [liuw086/SuperScreen#33]
![Pasha Kagan - 2024-03-07 01_41_53](https://github.com/liuw086/SuperScreen/assets/8081472/8a37b6b1-96e5-48c1-be59-8ed60b5aad0c)

**Comment by liuw086** [comment]
Thank you very much for your feedback. This is indeed a bug. I will deal with it immediately. I will package version 0.4.5 to fix this problem tomorrow Friday afternoon.

**Comment by liuw086** [comment]
0.4.5 has been released and online. This problem should have been fixed. Please try it. Thanks again for the feedback.
