### ISSUE TITLE
Hebrew subtitles appear in gibberish

### ISSUE THREAD

**Issue by PashaKagan** [liuw086/SuperScreen#34]
![Pasha Kagan - 2024-03-07 01_46_56](https://github.com/liuw086/SuperScreen/assets/8081472/bfa939f7-cb68-41db-bdb3-4aeb3825f707)

**Comment by liuw086** [comment]
Thanks for the reminder, is this how it should be? I found a font problem, which has been solved and will be fixed in version 0.4.5 tomorrow.
![image](https://github.com/liuw086/SuperScreen/assets/9710022/21e2856c-0081-4c77-8870-dfabcdd1fd3c)

**Comment by liuw086** [comment]
0.4.5 has been released and online. This problem should have been fixed. Please try it. Thanks again for the feedback.
