### ISSUE TITLE
Exit App using the Home button Quest controller

### ISSUE THREAD

**Issue by Pimpuss** [liuw086/SuperScreen#46]
When you want to exit the application using the "Home" button on the right controller of the Quest (like on other Apps) the application does not exit and crashes the Quest interface. Forced to restart the Quest..

**Comment by liuw086** [comment]
Thank you so much, I will try to reproduce it and see how to optimize it

**Comment by liuw086** [comment]
0.5.1 has been optimized to pause video playback when the menu appears to fix this problem.
