### ISSUE TITLE
The ray of the left handle is relatively short for adaptation.

### ISSUE THREAD

**Issue by liuw086** [liuw086/SuperScreen#50]
https://www.facebook.com/groups/oculusquest2tw/posts/1134979401268444/?comment_id=1142557830510601&notif_id=1712195475007743&notif_t=group_comment

**Comment by lunchanddinner** [comment]
Yes same issue here, on left controller the Pointing Line is quite short and doesn't reach to the end. Right controller is fine.
Using on Quest 3

**Comment by liuw086** [comment]
fix 0.5.6
